#!/usr/bin/env bash
# bashsupport disable=BP5001

# shellcheck source=./logr.sh
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/logr.sh"

# Prints the specified text as a section headline.
# Arguments:
#   1 - headline
#   2 - separator
# bashsupport disable=BP5005
SECTION() {
  printf "\n\n ─────── %s %s\n\n" "$1" "${2//-/─}"
}

SECTION failr ------------------------------------------------------------------
(failr) || true
(failr --) || true
(
  # bashsupport disable=BP5008
  foo() {
    [[ $1 == "baz" ]] || failr "baz expected" -u "baz" -- "$*"
  }
  foo bar
) || true

SECTION "util: inline" ---------------------------------------------------------
util -n inline 'foo'
util -n inline '
foo
bar
'
util -n inline '
foo
bar
baz
'

SECTION "util: center" ---------------------------------------------------------
util center '' && echo "|"
util center '✘' && echo "|"
util center -w 2 '👐' && echo "|"
declare var
util center -v var '12' && echo "$var|"
util center '123' && echo "|"
util center '1234' && echo "|"

SECTION "util: icon" -----------------------------------------------------------
printf ' ' && util icon success
printf ' ' && util icon warn
printf ' ' && util icon -v var error && echo "$var"
printf '%s' '->' && util icon -c new && printf '%s\n' '<-'

SECTION "util: print_margin" ---------------------------------------------------
for i in 0 1 2 3 4 5; do
  printf '%d' "$i"
  sleep 0.05
  util print_margin "⠤⠶⠿"
  sleep 0.05
done
echo

SECTION "util: print_line" -----------------------------------------------------
util -n print_line -i success 'existing icon + text'
util -n print_line 'text only'
util -n print_line --icon not-exists 'not existing icon + text'

SECTION "util: print_line_end" -------------------------------------------------
util print_line -i success 'existing-icon + text' && sleep 0.3 && util print_line_end -n -i success " -> icon + text updated"
util print_line 'text-only' && sleep 0.3 && util print_line_end -n -i success
util print_line -i not-exists 'not-existing icon + text' && sleep 0.3 && util print_line_end -n " -> text updated"

SECTION "main" -----------------------------------------------------------------
printf "%sBRIGHT%s %sBLACK%s\n" "$tty_bright_black" "$tty_reset" "$tty_black" "$tty_reset"
printf "%sBRIGHT%s %sRED%s\n" "$tty_bright_red" "$tty_reset" "$tty_red" "$tty_reset"
printf "%sBRIGHT%s %sGREEN%s\n" "$tty_bright_green" "$tty_reset" "$tty_green" "$tty_reset"
printf "%sBRIGHT%s %sYELLOW%s\n" "$tty_bright_yellow" "$tty_reset" "$tty_yellow" "$tty_reset"
printf "%sBRIGHT%s %sBLUE%s\n" "$tty_bright_blue" "$tty_reset" "$tty_blue" "$tty_reset"
printf "%sBRIGHT%s %sMAGENTA%s\n" "$tty_bright_magenta" "$tty_reset" "$tty_magenta" "$tty_reset"
printf "%sBRIGHT%s %sCYAN%s\n" "$tty_bright_cyan" "$tty_reset" "$tty_cyan" "$tty_reset"
printf "%sBRIGHT%s %sWHITE%s\n" "$tty_bright_white" "$tty_reset" "$tty_white" "$tty_reset"

SECTION "logr" -----------------------------------------------------------------
logr new "new message"
logr item "item message"
logr list "list message" "list message" "list message"
logr link "https://github.com/bkahlert"
logr link "https://example.com" "link text"
logr file "logr.sh" --line 300 --column 10
logr success "success message"
logr info "info message"
logr warn "warn message"
logr error "error message"
logr fail "failr message" || true

logr task "task message"
logr task "task message and cmdline" -- sleep 2
logr task --warn-only -- exit 2
(logr task -- bash -c '
echo foo && sleep 1
echo bar >&2 && sleep 1
echo baz >&2 && sleep 1
exit 2
') || true
